Rework help command to work on OpenBSD.

diff --git a/mr b/mr
--- a/mr
+++ b/mr
@@ -1637,24 +1637,26 @@ sub dispatch {
 
 sub help {
 	my $help=q#
-		case `uname -s` in
-			SunOS)
-			SHOWMANFILE="man -f"
-			;;
-			Darwin)
-			SHOWMANFILE="man"
-			;;
-			*)
-			SHOWMANFILE="man"
-			;;
-		esac
 		if [ ! -e "$MR_PATH" ]; then
 			error "cannot find program path"
 		fi
 		tmp=$(mktemp -t mr.XXXXXXXXXX) || error "mktemp failed"
 		trap "rm -f $tmp" exit
 		pod2man -c mr "$MR_PATH" > "$tmp" || error "pod2man failed"
-		$SHOWMANFILE "$tmp" || error "man failed"
+		showman() {
+			case `uname -s` in
+				SunOS)
+				man -f "$tmp"
+				;;
+				OpenBSD)
+				mandoc "$tmp" | $PAGER
+				;;
+				*)
+				man "$tmp"
+				;;
+			esac
+		}
+		showman "$tmp" || error "man failed"
 	#;
 	exec($help) || die "exec: $!";
 }
