merge git-svn support from Bastian Kleineidam's implementation
Adds register command, and better tests. Use git-svn log. I left the update
command using git-svn fetch instead of git-svn rebase for now, may change this
later.

diff --git a/lib/git-svn b/lib/git-svn
--- a/lib/git-svn
+++ b/lib/git-svn
@@ -4,13 +4,27 @@
 # section of your ~/.mrconfig
 #include = cat /usr/share/mr/git-svn
 
-git_test = test -d "$MR_REPO"/.git && ! test -d "$MR_REPO"/.git/svn/git-svn
-git_svn_test = test -d "$MR_REPO"/.git/svn/git-svn
+git_test =
+	test -d "$MR_REPO"/.git &&
+	test -z "`git config --get svn-remote.svn.url`"
+
+git_svn_test =
+	test -d "$MR_REPO"/.git &&
+	test -n "`git config --get svn-remote.svn.url`"
+
+git_svn_register =
+	url="`LC_ALL=C git config --get svn-remote.svn.url`" || true
+	if [ -z "$url" ]; then
+		error "cannot determine git-svn url"
+	fi
+	echo "Registering git-svn url: $url in $MR_CONFIG"
+	mr -c "$MR_CONFIG" config "`pwd`" checkout="git-svn clone '$url' '$MR_REPO'"
+
 git_svn_update = git-svn fetch
 git_svn_status = git status "$@" || true
 git_svn_commit = git-svn dcommit
 git_svn_record = git commit -a "$@"
 git_svn_diff = git diff "$@"
-git_svn_log = git log "$@"
+git_svn_log = git-svn log "$@"
 
 # vim:sw=8:sts=0:ts=8:noet
